name: Reseed the DB at 12:00 every month

on:
  schedule:
    - cron: '0 12 * */1 *'

jobs:
  get_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make GET Request to re-seed the DB
        run: curl https://inteligets.up.railway.app/api/seed
